add homework 34
volodymyrrusin/robot_dreams-python_developer pull request #18
Opened 2023-04-10 10:32 UTC by volodymyrrusin

Please check my lesson 34 homework

2023-04-10 13:35 UTC, klymenok requested changes

2023-04-10 13:35 UTC, klymenok commented on flask-homework/robot_app/templates/login.html
> +        <input type='password' name='password' value='' minlength='8' pattern='^(.*[A-Z])(.*[0-9]).*$' placeholder="Password"/>
Ваш валідатор не приймає маленьких літер

2023-04-10 14:37 UTC, volodymyrrusin commented on flask-homework/robot_app/templates/login.html
> +        <input type='password' name='password' value='' minlength='8' pattern='^(.*[A-Z])(.*[0-9]).*$' placeholder="Password"/>
Вибачаюсь, але не розумію зауваження. 
Здається ж він працює згідно умови попередьої домашки - "Password має містити мінімум 1 цифру і 1 велику літеру, має бути не менше ніж 8 символів". Чи що саме не так, поясніть будь ласка?

2023-04-12 21:10 UTC, klymenok commented on flask-homework/robot_app/templates/login.html
> +        <input type='password' name='password' value='' minlength='8' pattern='^(.*[A-Z])(.*[0-9]).*$' placeholder="Password"/>
Чисто технічно ваша реалізація відповідає вимогам завдання. Але з точки зору user experience, не дуже логічно щоб пароль взагалі не міг містити маленьких літер. Наприклад, валідні паролі:
```
QWERTY12
QWERASD1
```
Але в той же час невалідними будуть
```
qWERTY12
QwErAsD1
```

2023-04-13 11:27 UTC, volodymyrrusin commented on flask-homework/robot_app/templates/login.html
> +        <input type='password' name='password' value='' minlength='8' pattern='^(.*[A-Z])(.*[0-9]).*$' placeholder="Password"/>
Так у мене ж наче проходять валідацію паролі з маленькими буквами, як ті що ви вказали так і будь-які інші. Саме тому не розумію що від мене вимагається тут.

2023-04-20 20:12 UTC, klymenok approved these changes

2023-04-21 09:57 UTC, volodymyrrusin commented on flask-homework/robot_app/templates/login.html
> +        <input type='password' name='password' value='' minlength='8' pattern='^(.*[A-Z])(.*[0-9]).*$' placeholder="Password"/>
Дякую, спробую розібратись з цим до кінця.

2023-04-21 09:57 UTC, merged